---
- name: Deploy Java Application
  hosts: app
  become: true

  tasks:

    - name: Create application directory
      ansible.builtin.file:
        path: /opt/devops-webapp
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Stop old container
      community.docker.docker_container:
        name: devops-webapp
        state: absent

    - name: Copy application JAR
      ansible.builtin.copy:
        src: /devops-java-webapp/target/devops-webapp.jar
        dest: /opt/devops-webapp/devops-webapp.jar
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy Dockerfile
      ansible.builtin.copy:
        src: /devops-java-webapp/Dockerfile
        dest: /opt/devops-webapp/Dockerfile
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Build Docker image
      community.docker.docker_image:
        name: devops-webapp
        tag: latest
        source: build
        build:
          path: /opt/devops-webapp
          dockerfile: Dockerfile

    - name: Start application container
      community.docker.docker_container:
        name: devops-webapp
        image: devops-webapp:latest
        state: started
        restart_policy: always
        ports:
          - "8081:8081"

    - name: Wait for application
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 8081
        delay: 5
        timeout: 60

    - name: Verify application
      ansible.builtin.uri:
        url: http://127.0.0.1:8081
        status_code: 200
